### ISSUE TITLE
expose response status

### ISSUE THREAD

**Issue by eis** [binout/jaxrs-unit#1]
Trying to use [response](https://github.com/binout/jaxrs-unit/blob/master/jaxrs-unit-api/src/main/java/io/github/binout/jaxrsunit/JaxrsResponse.java) immediately hits into issues, since you can only assert a couple of pre-defined statuses. Why not expose isStatus() so user can test whatever status?

Considering a fork just to have that. Code looks otherwise nice and clean.

**Comment by eis** [comment]
Did a simple helper class, since otherwise this lib seems useful and clean:

```
package io.github.binout.jaxrsunit.resteasy;

import io.github.binout.jaxrsunit.JaxrsResponse;
import io.github.binout.jaxrsunit.resteasy.RestEasyResponse;

import javax.ws.rs.core.Response;

public class ResteasyResponseTestHelper {

    public static boolean isStatus(JaxrsResponse response, Response.Status status) {
        return ((RestEasyResponse)response).isStatus(status);
    }
}
```

**Comment by binout** [comment]
Do you need a new release  (1.1.1) on Maven Central ?

**Comment by eis** [comment]
@binout it could be nice! Though consider Provider support as well. (#5)
